# Generated by Django 4.2 on 2023-04-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('ambient_light', models.FloatField()),
                ('barometric_pressure', models.FloatField()),
                ('sound_noise', models.FloatField()),
                ('etvoc', models.FloatField()),
                ('eco2', models.FloatField()),
                ('discomfort_index', models.FloatField()),
                ('heat_stroke', models.FloatField()),
                ('vibration_information', models.FloatField()),
                ('si_value', models.FloatField()),
                ('pga', models.FloatField()),
                ('seismic_intensity', models.FloatField()),
            ],
            options={
                'verbose_name_plural': '環境データ',
                'db_table': 'environment',
                'ordering': ['-measure_time'],
            },
        ),
    ]
