# Generated by Django 4.2 on 2023-04-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomenvironment',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
