# Generated by Django 4.2 on 2023-04-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_roomenvironment_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomenvironment',
            name='place',
            field=models.CharField(max_length=50),
        ),
    ]
